import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Header from '../components/Header'
import Footer from '../components/Footer'

const roboto = 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap';
const monserrat = 'https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap';

export const metadata: Metadata = {
  title: "Test task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel='stylesheet' href={roboto} />
        <link rel='stylesheet' href={monserrat} />
      </head>
      <body className='relative'>
        <Image className="front-image z-0" src={"/Vector1.png"} alt={"front image"} width={604} height={423} />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
